### ISSUE TITLE
Online-based information

### ISSUE THREAD

**Issue by AFAgarap** [MBoustani/Georeverse#1]
Wouldn't it be better if instead of having the list of locations in a `csv` file, just have the program retrieve information, say, Google Maps? :)

**Comment by MBoustani** [comment]
@AFAgarap that's a good idea, I am not going to use Google Maps as it's not free and has rate limits.
But what I can do is simply paste the content of CSV into georeverse.py for now.

**Comment by MBoustani** [comment]
@AFAgarap 
Please try  `pip install georeverse --upgrade`
There is no need to copy `world_cities.csv` anymore.

**Comment by AFAgarap** [comment]
@MBoustani Isn't that kind of bulky then? :)

**Comment by MBoustani** [comment]
@AFAgarap 
- not very bulky, file size is around 600k
- I believe not many user would be happy if the program they use download a file into their local machine.

**Comment by MBoustani** [comment]
@AFAgarap 
Have you tried the new version? Feedback?

**Comment by AFAgarap** [comment]
@MBoustani I will try it later this day :)
